version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build 
            - ls -a
artifacts:
# IMPORTANT - Please verify your build output directory
    base-directory:
        dist
    files:
        - '**/*'
cache:
    paths:
        - node_modules/**/*